### ISSUE TITLE
request: rar2fs

### ISSUE THREAD

**Issue by KyleSanderson** [pfnet-research/meta-fuse-csi-plugin#1]
hi - I use https://github.com/hasse69/rar2fs which provides a transparent FUSE filesystem for transparently exposing archive contents to a filesystem. The dockerfile feels beyond me, but I need to be able to pass mount options to the application.

**Comment by naoki9911** [comment]
Thank you for opening the first issue!

rar2fs seems to use libfuse, so "fusermount3-proxy" mount approach should work.

fusermount3-proxy approach is configured by injecting dedicated fusermount3-proxy binary to rar2fs container image.
This dockerfile example shows the procedure to inject fusermount3-proxy binary.
https://github.com/pfnet-research/meta-fuse-csi-plugin/blob/main/examples/proxy/mountpoint-s3/Dockerfile

If you want to pass command line arguments to rar2fs, you can pass them as this mountpoint-s3 example. 

https://github.com/pfnet-research/meta-fuse-csi-plugin/blob/437dbbbbf16e5b02f9a508e3403d044b0a9dff89/examples/proxy/mountpoint-s3/deploy.yaml#L17

**Comment by naoki9911** [comment]
I think meta-fuse-csi-plugin works with rar2fs, and examples will help you to write manifest.
If you have problems, could you reopen this issue and provide error details?
