### ISSUE TITLE
Update public image for mountpoint-s3

### ISSUE THREAD

**Issue by jy-frankfan** [pfnet-research/meta-fuse-csi-plugin#9]
The current image in GHCR is quite old, I noticed that the Dockerfile had been updated for a while but seems like no image has been pushed yet.
Can you please rebuild the image for:
ghcr.io/pfnet-research/meta-fuse-csi-plugin/mfcp-example-proxy-mountpoint-s3:latest

Thank you!

**Comment by jy-frankfan** [comment]
Hi @naoki9911 can you please kindly suggest if above can be handled?

**Comment by naoki9911** [comment]
@jy-frankfan 
Thank you for your notification!
I missed your comment, I will update the image.

**Comment by naoki9911** [comment]
I have released new images.
